GET http://localhost:5151/games

###
GET http://localhost:5151/games/3

###
POST http://localhost:5151/games
Content-Type: application/json 

{
    "name": "Avatar the last airbender",
    "genreId": 5,
    "price": 1.99,
    "releaseDate": "2011-11-18"
}

###
PUT http://localhost:5151/games/3
Content-Type: application/json

{
    "name": "Street Fighter Turbo",
    "genreId": 1,
    "price": 19.99,
    "releaseDate": "1992-02-01"
}

###
DELETE http://localhost:5151/games/2
